# Generated by Django 6.0.6 on 2026-06-16 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('vibration', models.FloatField()),
                ('pressure', models.FloatField()),
                ('current', models.FloatField()),
                ('rpm', models.FloatField()),
                ('oil_level', models.FloatField()),
                ('noise_level', models.FloatField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('source', models.CharField(default='simulator', max_length=20)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='machines.machine')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['machine', 'timestamp'], name='sensors_sen_machine_916b74_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=50)),
                ('warning_min', models.FloatField(blank=True, null=True)),
                ('warning_max', models.FloatField(blank=True, null=True)),
                ('critical_min', models.FloatField(blank=True, null=True)),
                ('critical_max', models.FloatField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='machines.machine')),
            ],
            options={
                'unique_together': {('machine', 'sensor_type')},
            },
        ),
    ]
